server:
  port: 2020

#spring data src

spring:
  datasource:
    username: root
    password: 4562
    url: jdbc:mysql://localhost/spring

  jpa:
    show-sql: true
    generate-ddl: true  # for printing sql query in the console
    hibernate:
      ddl-auto: update


